# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0079_populate_msg_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='flow_rules',
            field=models.TextField(help_text='Flow rules serialized', null=True, verbose_name='Flow rules'),
        ),
    ]
